#!/usr/bin/with-contenv bash
## load /etc/environment vars first:
 for line in $( cat /etc/environment ) ; do export $line ; done

# set up kubernetes configuration
K8S=https://$KUBERNETES_SERVICE_HOST:$KUBERNETES_SERVICE_PORT
TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
CACERT=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
NAMESPACE=$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)

# check k8s health
curl -H "Authorization: Bearer $TOKEN" --cacert $CACERT $K8S/healthz

# update launcher.kubernetes.conf file
cat << EOF > /etc/rstudio/launcher.kubernetes.conf
api-url=$K8S
auth-token=$TOKEN
profile-conf=/etc/rstudio/launcher.kubernetes.profile.conf
EOF

mkdir -p /usr/local/share/ca-certificates/Kubernetes
cat $CACERT > /usr/local/share/ca-certificates/Kubernetes/cert-Kubernetes.crt
update-ca-certificates

# start sssd
# we should really be a bit more sophisticated...
sssd

exec /usr/lib/rstudio-server/bin/rstudio-launcher
