version: '2.3'
services:

  apache-simple:
    hostname: apache-simple
    image: httpd:2.4
    volumes:
      - ./cluster/apache-simple.conf:/usr/local/apache2/conf/httpd.conf
    ports:
      - "80"

# from support article
# https://support.rstudio.com/hc/en-us/articles/213733868-Running-Shiny-Server-with-a-Proxy
  apache-support-ssp:
    hostname: apache-support-ssp
    image: httpd:2.4
    volumes: 
      - ./cluster/apache-support-ssp.conf:/usr/local/apache2/conf/httpd.conf
    ports:
      - "80"

# from support article
# https://support.rstudio.com/hc/en-us/articles/200552326-Running-RStudio-Server-with-a-Proxy
  apache-support-rsp:
    hostname: apache-support-rsp
    image: httpd:2.4
    volumes: 
      - ./cluster/apache-support-rsp.conf:/usr/local/apache2/conf/httpd.conf
    ports:
      - "80"

