version: '2.3'
services:

  base-rsp:
    hostname: base-rsp
    command: bash
    build:
      context: ./cluster
      dockerfile: base-rsp/Dockerfile
    environment:
      - RSP_LICENSE
    ports:
      - 8787:8787
