version: '2.3'
services:

  k-server-minimal:
    build:
      context: ./server
#    volumes:
#      - ./server/krb5.conf:/etc/krb5.conf
#      - ./server/kdc.conf:/var/kerberos/krb5kdc/kdc.conf
#      - ./server/kadm5.acl:/var/kerberos/krb5kdc/kadm5.acl
  k-client:
    build:
      context: ./server
      dockerfile: client.Dockerfile
    links:
      - k-server-minimal
