version: '2.3'
services:

  k-ssh-client:
    hostname: k-ssh-client
    build:
      context: ./cluster
      dockerfile: ssh-client/Dockerfile
    links:
      - k-server
      - k-ssh-server
  k-ssh-server:
    hostname: k-ssh-server
    build:
      context: ./cluster
      dockerfile: ssh-server/Dockerfile
    links:
      - k-server

networks:
  default:
    external:
      name: ${NETWORK}
