version: '2.3'
services:

  k-server:
    hostname: k-server
    build:
      context: ./cluster
      dockerfile: server/Dockerfile
  k-simple-client:
    hostname: k-simple-client
    build:
      context: ./cluster
      dockerfile: simple-client/Dockerfile
    links:
      - k-server

networks:
  default:
    external:
      name: ${NETWORK}

