version: '2.3'
services:
  oauth2-proxy:
    image: a5huynh/oauth2_proxy
    environment:
      # .env file with ENV_VAR_NAME=value, one per line.
      - OAUTH2_PROXY_CLIENT_ID=${OAUTH2_PROXY_CLIENT_ID}
      - OAUTH2_PROXY_CLIENT_SECRET=${OAUTH2_PROXY_CLIENT_SECRET}
      - OAUTH2_PROXY_COOKIE_SECRET=${OAUTH2_PROXY_COOKIE_SECRET}
      - OAUTH2_HOST=${OAUTH2_HOST}
    command: 
      - --provider=github
      - --http-address=http://0.0.0.0:80
      - --upstream=http://oauth2-connect:3939/
      - --redirect-url=http://${OAUTH2_HOST}/oauth2/callback
      - --email-domain=*
      - --cookie-secure=false
    ports:
      - "80:80"

  oauth2-connect:
    hostname: oauth2-connect
    build:
      context: ./cluster
      dockerfile: oauth2-connect/Dockerfile
      args:
        - CONNECT_BINARY_URL=rstudio-connect_1.6.6.1-4_amd64.deb
    privileged: true
    environment:
      - CONNECT_LICENSE
    ports:
      - 3939:3939
    links:
      - oauth2-proxy
