version: '2.3'
services:
  oauth2-proxy:
    image: a5huynh/oauth2-proxy
    environment:
      # .env file with ENV_VAR_NAME=value, one per line.
      - OAUTH2_PROXY_CLIENT_ID=${OAUTH2_PROXY_CLIENT_ID}
      - OAUTH2_PROXY_CLIENT_SECRET=${OAUTH2_PROXY_CLIENT_SECRET}
      - OAUTH2_PROXY_COOKIE_SECRET=${OAUTH2_PROXY_COOKIE_SECRET}
      - OAUTH2_HOST=${OAUTH2_HOST}
    command: 
      - oauth2_proxy
      - --provider=github
      - --http-address=http://0.0.0.0:80
      - --upstream=http://${OAUTH2_HOST}:3939/
      - --redirect-url=http://${OAUTH2_HOST}/oauth2/callback
      - --email-domain=*
      - --cookie-secure=false
    ports:
      - "80:80"

