apiVersion: apps/v1
kind: Deployment
metadata:
  name: launcher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: launcher
  template:
    metadata:
      labels:
        app: launcher
    spec:
      containers:
      - name: launcher
        image: rstudio/launcher-ldap
        #args: ["/usr/lib/rstudio-server/bin/rstudio-launcher"]
        #command: ["sleep","10000"]
        imagePullPolicy: Never
        ports:
        - containerPort: 5559
---
apiVersion: v1
kind: Service
metadata:
  name: launcher
spec:
  type: NodePort
  selector:
    app: launcher
  ports:
  - port: 5559
