---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  rspm.conf: |
    server {
      listen 80;
      # this takes care of redirecting /packages to /packages/
      rewrite ^/packages$ $scheme://$http_host/packages/;

      # Proxy RStudio Package manager at /packages/
    location /packages/ {
        rewrite ^/packages/(.*)$ /$1 break;
        proxy_set_header    X-RSPM-Request $scheme://$http_host$request_uri;
        proxy_pass http://rstudio-pm.soleng.svc.cluster.local;
        proxy_redirect / $scheme://$http_host/packages/;
    }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        volumeMounts:
        - mountPath: /etc/nginx/conf.d
          name: nginx-config
        ports:
        - containerPort: 80
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
---

apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
  - port: 80
