apiVersion: apps/v1
kind: Deployment
metadata:
  name: rsp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rsp
  template:
    metadata:
      labels:
        app: rsp
    spec:
      containers:
      - name: rsp
        image: rstudio/rstudio-server-pro:daily
        env:
        - name: RSP_LICENSE
          valueFrom:
            secretKeyRef:
              name: license
              key: rsp
        #command: ["sleep","10000"]
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8787
        securityContext:
          privileged: true
---
apiVersion: v1
kind: Service
metadata:
  name: rsp
spec:
  type: NodePort
  selector:
    app: rsp
  ports:
  - port: 80
    targetPort: 8787
