apiVersion: apps/v1
kind: Deployment
metadata:
  name: rsw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rsw
  template:
    metadata:
      labels:
        app: rsw
    spec:
      containers:
      - name: rsw
        image: rstudio/rstudio-workbench:latest
        env:
        - name: RSW_LICENSE
          valueFrom:
            secretKeyRef:
              name: license
              key: rsw
        #command: ["sleep","10000"]
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8787
        securityContext:
          privileged: true
---
apiVersion: v1
kind: Service
metadata:
  name: rsw
spec:
  type: NodePort
  selector:
    app: rsw
  ports:
  - port: 80
    targetPort: 8787
