version: '2.3'
services:
  base-rsp:
    image: rstudio/rstudio-server-pro:${RSTUDIO_VERSION}
    privileged: true
    environment:
      RSP_LICENSE: ${RSP_LICENSE}
    ports:
      - "8787"
    volumes:
      - ../config/case-1.sh:/usr/local/bin/startup.sh
 
