version: "2.3"
services:
  saml-idp:
    hostname: saml-idp
    image: kristophjunge/test-saml-idp
    ports:
      - 8080:8080
      - 8443:8443
    environment:
      - SIMPLESAMLPHP_SP_ENTITY_ID=apache-saml
      - SIMPLESAMLPHP_SP_ASSERTION_CONSUMER_SERVICE=https://localhost/secret/postResponse
      - SIMPLESAMLPHP_SP_SINGLE_LOGOUT_SERVICE=https://localhost/secret/logout
    volumes:
      - ../cluster/users.php:/var/www/simplesamlphp/config/authsources.php

  apache-saml:
    hostname: apache-saml
    build:
      context: ../cluster
      dockerfile: apache-saml/Dockerfile
    volumes:
      - ../cluster/apache-saml-all.conf:/usr/local/apache2/conf/httpd.conf
    ports:
      - "80:80"
      - "443:443"
      - "8991"
