version: '2.3'
services:

  rstudio-proxy:
    hostname: rstudio-proxy
    build:
      context: ../cluster
      dockerfile: rstudio-proxy/Dockerfile
    environment:
      - RSP_LICENSE
    ports:
      - 8788:8787
    links:
      - apache-auth

  apache-auth:
    hostname: apache-auth
    build:
      context: ../cluster
      dockerfile: apache-auth/Dockerfile
    ports:
      - 80:80

