version: '2.3'
services:

  base-rsp:
    hostname: base-rsp
    build:
      context: ../cluster
      dockerfile: base-rsp/Dockerfile
      args:
        - RSTUDIO_VERSION=${RSTUDIO_VERSION}
    image: rstudio/sol-eng-rstudio:${RSTUDIO_VERSION}
    environment:
      - RSP_LICENSE
    ports:
      - "8787"
      - "443"

  rsp-ldap:
    hostname: rsp-ldap
    build:
      context: ../cluster
      dockerfile: rsp-ldap/Dockerfile
      args:
        - RSTUDIO_VERSION=${RSTUDIO_VERSION}
    image: rstudio/sol-eng-rstudio:ldap-${RSTUDIO_VERSION}
    environment:
      - RSP_LICENSE
    ports:
      - "8787"
      - "443"
 
