version: '2.3'
services:

  connect:
    hostname: connect
    build:
      context: ../cluster
      dockerfile: ./base-connect/Dockerfile
      args:
        - CONNECT_BINARY_URL=${CONNECT_BINARY_URL}
    ports:
      - 3939:3939
    privileged: true
    environment:
      - CONNECT_LICENSE

