version: '2.3'
services:

  connect:
    hostname: connect
    image: rstudio/rstudio-connect:${CONNECT_VERSION}
    ports:
      - 3939
    privileged: true
    environment:
      - RSC_LICENSE
    volumes:
      - ../cluster/base-connect.gcfg:/etc/rstudio-connect/rstudio-connect.gcfg

