version: '2.3'
services:

  k-connect:
    hostname: k-connect
    build:
      context: ../cluster
      dockerfile: k-connect/Dockerfile
      args:
        - CONNECT_BINARY_URL=rstudio-connect_1.6.6.1-4_amd64.deb
    ports:
      - 3939:3939
    privileged: true
    environment:
      - CONNECT_LICENSE
    links:
      - k-server
