version: '2.3'
services:

  kerb-connect:
    hostname: kerb-connect
    image: rstudio/sol-eng-connect:kerberos-${CONNECT_VERSION}
    build:
      context: ../cluster
      dockerfile: kerberos-connect/Dockerfile
      args:
        - CONNECT_VERSION=${CONNECT_VERSION}
    ports:
      - "3939"
    privileged: true
    environment:
      - RSC_LICENSE
    volumes:
      - "../cluster/kerberos-connect/rstudio-connect.gcfg:/etc/rstudio-connect/rstudio-connect.gcfg"

  sut:
    image: rstudio/sol-eng-connect:kerberos-${CONNECT_VERSION}
    privileged: true
    command: /run_tests.sh
    entrypoint: []
    volumes:
     - "../test/run_tests.sh:/run_tests.sh"
     - "../test/kerb-connect.yaml:/tmp/goss.yaml"
