version: '2.3'
services:

  kerb-ldap-rsp:
    hostname: kerb-ldap-rsp
    build:
      context: ../cluster
      dockerfile: kerb-ldap-rsp/Dockerfile
      args:
        - RSTUDIO_VERSION=${RSTUDIO_VERSION}
    image: rstudio/sol-eng-rstudio:kerberos-ldap-${RSTUDIO_VERSION}
    privileged: true
    ports:
      - "8787"
    environment:
      - RSW_LICENSE
      - RSW_TESTUSER=
    volumes:
     - "../cluster/krb5.conf:/etc/krb5.conf"
     - "../cluster/kerb-postgres-odbc.ini:/etc/odbc.ini"
