version: '2.3'
services:

  kerb-rsp:
    hostname: kerb-rsp
    build:
      context: ../cluster
      dockerfile: kerberos-rstudio/Dockerfile
      args:
        - RSTUDIO_VERSION=${RSTUDIO_VERSION}
    image: rstudio/sol-eng-rstudio:kerberos-${RSTUDIO_VERSION}
    privileged: true
    ports:
      - "8787"
    environment:
      - RSP_LICENSE
      - RSP_TESTUSER=

  sut:
    image: rstudio/sol-eng-rstudio:kerberos-${RSTUDIO_VERSION}
    privileged: true
    environment:
      - RSP_LICENSE
      - RSP_TESTUSER=
    command: /run_tests.sh
    entrypoint: []
    volumes:
     - "../test/run_tests.sh:/run_tests.sh"
     - "../test/kerb-rsp.yaml:/tmp/goss.yaml"
