version: '3.3'
services:

  launcher-rsp-ldap:
    hostname: launcher-rsp-ldap
    image: compose_launcher-rsp-ldap
    build:
      context: ../cluster
      dockerfile: launcher-rsp-ldap/Dockerfile
    environment:
      - RSP_LICENSE
    ports:
      - 8787:8787

  launcher-ldap:
    hostname: launcher-ldap
    image: compose_launcher-ldap
    build:
      context: ../cluster
      dockerfile: launcher-ldap/Dockerfile
    environment:
      - RSP_LICENSE
    ports:
      - 5559:5559

  launcher-session:
    hostname: launcher-session
    image: colearendt/rsession-demo:prelaunch
    build:
      context: ../cluster
      dockerfile: launcher-session/Dockerfile
      args:
        R_VERSION: "3.5.1"

