version: '3.3'
services:

  launcher-rsp:
    hostname: launcher-rsp
    image: compose_launcher-rsp:4
    build:
      context: ../cluster
      dockerfile: launcher-rsp/Dockerfile
    environment:
      - RSP_LICENSE
    ports:
      - 8787:8787

  launcher-session:
    hostname: launcher-session
    image: colearendt/rsession-demo:prelaunch
    build:
      context: ../cluster
      dockerfile: launcher-session/Dockerfile
      args:
        R_VERSION: "3.5.1"

