version: '2.3'
services:

  ldap-rsp:
    hostname: ldap-rsp
    image: ghcr.io/rstudio/rstudio-workbench:${RSTUDIO_VERSION}
    privileged: true
    volumes:
      - "../cluster/ldap-rsp.conf:/etc/rstudio/rserver.conf"
      - "../cluster/sssd.conf:/etc/sssd/sssd.conf"
      # - "../cluster/rsp-startup.sh:/usr/local/bin/startup.sh"
    environment:
      - "RSW_LICENSE"
    ports:
      - "8787"
