version: '2.3'
services:

  ldap-kerberos-rsp:
    hostname: ldap-kerberos-rsp
    build:
      context: ../cluster
      dockerfile: ldap-kerberos-rsp/Dockerfile
      args:
        - RSTUDIO_VERSION=${RSTUDIO_VERSION}
    image: rstudio/sol-eng-rstudio:ldap-kerberos-${RSTUDIO_VERSION}
    volumes:
      - ../cluster/ldap-kerberos-rsp/rserver.conf:/etc/rstudio/rserver.conf
      - ../cluster/rstudio-kerberos-sssd:/etc/pam.d/rstudio
      - ../cluster/rstudio-session-kerberos-sssd:/etc/pam.d/rstudio-session
    environment:
      - RSP_LICENSE
    ports:
      - "8787"
      - "443"
