version: '2.3'
services:

  openldap:
    hostname: openldap
    image: osixia/openldap
    ports:
       #- "389"
       - "636"
    volumes:
      - "./users.ldif:/container/service/slapd/assets/config/bootstrap/ldif/50-bootstrap.ldif"
    command:
      - ["--copy-service"]

  admin:
    hostname: admin
    image: osixia/phpldapadmin
    ports:
      - "443"
      - "80"
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=openldap
    links:
      - openldap
