version: '2.3'
services:

  ldap-rsp:
    hostname: ldap-rsp
    build:
      context: ../cluster
      dockerfile: ldap-rsp/Dockerfile
      args:
        - RSTUDIO_VERSION=${RSTUDIO_VERSION}
    image: rstudio/sol-eng-rstudio:ldap-${RSTUDIO_VERSION}
    privileged: true
    volumes:
      - ../cluster/ldap-rsp.conf:/etc/rstudio/rserver.conf
      - "~/Downloads/rsp-cole-license-2020-12-30.lic:/etc/rstudio/license.lic"
      - "../cluster/rsp-startup.sh:/usr/local/bin/startup.sh"
    #environment:
    #  - RSP_LICENSE
    ports:
      - "8787"
      - "443"
