version: '2.3'
services:

  ldap-rsp:
    hostname: ldap-rsp
    build:
      context: ../cluster
      dockerfile: ldap-rsp/Dockerfile
      args:
        - RSTUDIO_VERSION=${RSTUDIO_VERSION}
    image: rstudio/sol-eng-rstudio:ldap-${RSTUDIO_VERSION}
    privileged: true
    volumes:
      - "../cluster/ldap-rsp.conf:/etc/rstudio/rserver.conf"
      - "../cluster/rsp-startup.sh:/usr/local/bin/startup.sh"
    environment:
      - "RSP_LICENSE"
      - "RSP_LAUNCHER=true"
    ports:
      - "8787"
