version: '2.3'
services:

  connect:
    hostname: connect
    build:
      context: ../cluster
      dockerfile: ./ldap-connect/Dockerfile
      args:
        - CONNECT_BINARY_URL=rstudio-connect_1.6.8.2-12_amd64.deb
    ports:
      - 3939:3939
    privileged: true
    environment:
      - CONNECT_LICENSE
    depends_on:
      pg-connect:
        condition: service_healthy

  pg-connect:
    hostname: pg-connect
    image: postgres:10
    environment:
      POSTGRES_PASSWORD: test
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5


