version: "2.3"
services:

  proxy-connect:
    hostname: proxy-connect
    build:
      context: ../cluster
      dockerfile: base-connect/Dockerfile
      args:
        - CONNECT_BINARY_URL
    privileged: true
    volumes:
      - ../cluster/proxy-connect.gcfg:/etc/rstudio-connect/rstudio-connect.gcfg
    environment:
      - CONNECT_LICENSE

    
