version: '2.3'
services:

  apache-simple:
    hostname: apache-simple
    image: httpd:2.4
    volumes:
      - ../cluster/apache-simple.conf:/usr/local/apache2/conf/httpd.conf
    ports:
      - "80"

# from support article
# https://support.rstudio.com/hc/en-us/articles/213733868-Running-Shiny-Server-with-a-Proxy
  apache-support-ssp:
    hostname: apache-support-ssp
    image: httpd:2.4
    volumes: 
      - ../cluster/apache-support-ssp.conf:/usr/local/apache2/conf/httpd.conf
    ports:
      - "80"

  nginx-support-ssp:
    hostname: nginx-support-ssp
    image: nginx
    volumes:
      - ../cluster/nginx-support-ssp.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80"

# from support article
# https://support.rstudio.com/hc/en-us/articles/200552326-Running-RStudio-Server-with-a-Proxy
  apache-support-rsp:
    hostname: apache-support-rsp
    image: httpd:2.4
    volumes: 
      - ../cluster/apache-support-rsp.conf:/usr/local/apache2/conf/httpd.conf
    ports:
      - "80"

  apache-support-rsp-ha:
    hostname: apache-support-rsp-ha
    image: httpd:2.4
    volumes: 
      - ../cluster/apache-support-rsp-ha.conf:/usr/local/apache2/conf/httpd.conf
    ports:
      - "80"

  apache-support-ssp-ha:
    hostname: apache-support-ssp-ha
    image: httpd:2.4
    volumes: 
      - ../cluster/apache-support-ssp-ha.conf:/usr/local/apache2/conf/httpd.conf
    ports:
      - "80"

  nginx-support-rsp:
    hostname: nginx-support-rsp
    image: nginx
    volumes:
      - ../cluster/nginx-support-rsp.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80"

  nginx-all:
    hostname: nginx-all
    image: nginx
    volumes:
      - ../cluster/nginx-all.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80"
