version: '2.3'
services:

  proxy-rsp:
    hostname: proxy-rsp
    image: rstudio/rstudio-server-pro:${RSTUDIO_VERSION}
    #image: rstudio/sol-eng-rstudio:ldap-${RSTUDIO_VERSION}
    environment:
      - RSP_LICENSE
    ports:
      - "8787"
    privileged: true
    volumes:
      - ../cluster/secure-proxy-user-header:/etc/rstudio/secure-proxy-user-header
      - ../cluster/proxy-rsp-launcher.conf:/etc/rstudio/rserver.conf
      - ../cluster/launcher.conf:/etc/rstudio/launcher.conf
      - ../cluster/rstudio-session:/etc/pam.d/rstudio-session
      - ../cluster/rstudio-session:/etc/pam.d/rstudio
