version: '2.3'
services:

  proxy-nginx-connect:
    hostname: proxy-nginx-connect
    image: nginx
    volumes:
      - ../cluster/nginx-connect.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80"
      - "443"
