version: '2.3'
services:

  proxy-rsp:
    hostname: proxy-rsp
    build:
      context: ../cluster
      dockerfile: base-rsp/Dockerfile
    environment:
      - RSP_LICENSE
    ports:
      - "8787"
    volumes:
      - ../cluster/secure-proxy-user-header:/etc/rstudio/secure-proxy-user-header
      - ../cluster/proxy-rsp.conf:/etc/rstudio/rserver.conf
