version: '3.3'
services:

  debug-session:
    hostname: debug-session
    image: colearendt/r-session-debug:${RSP_VERSION}-tcpdump
    build:
      context: ../cluster
      dockerfile: r-session-debug/Dockerfile
      args:
        R_VERSION: "3.5.1"
        RSP_VERSION: ${RSP_VERSION}
