version: '2.3'
services:

  rsp:
    image: rstudio/rstudio-workbench:${RSTUDIO_VERSION}
    privileged: true
    environment:
      RSW_LICENSE: ${RSW_LICENSE}
    ports:
       - "8787"
    volumes:
      - ../cluster/rsp-load-balancer:/etc/rstudio/load-balancer
      - ../cluster/rsp-ha-rserver.conf:/etc/rstudio/rserver.conf
      - ../cluster/rsp-ha-database.conf:/etc/rstudio/database.conf
      - ../cluster/secure-cookie-key:/etc/rstudio/secure-cookie-key
      - ../cluster/launcher-ha.conf:/etc/rstudio/launcher.conf
      - ../cluster/launcher.pem:/etc/rstudio/launcher.pem
      - ../cluster/launcher.pub:/etc/rstudio/launcher.pub
      - ../cluster/startup-launcher.sh:/usr/local/bin/startup-launcher.sh
      - ../cluster/startup.sh:/usr/local/bin/startup.sh
      - ../cluster/rstudio-launcher.conf:/startup/launcher/rstudio-launcher.conf
      - /efs/home:/home
      - launcher-scratch:/var/lib/rstudio-launcher/Local
    depends_on:
      pg-rsp:
        condition: service_healthy

  proxy:
    image: nginx
    ports:
      - "80:80"
    volumes:
          - ../cluster/nginx-rsp-ha.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - rsp

  pg-rsp:
    hostname: pg-rsp
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: test
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ../cluster/pg-init-rstudio.sh:/docker-entrypoint-initdb.d/init-db.sh

volumes:
  rsp-home-vol:
  launcher-scratch:
