version: '3.7'
services:

  rsp1:
    hostname: rsp1
    image: rstudio/rstudio-workbench:${RSTUDIO_VERSION}
    privileged: true
    environment:
      RSP_LICENSE: ${RSP_LICENSE}
    ports:
       - "8787"
    volumes:
      - ../cluster/rsp-load-balancer:/etc/rstudio/load-balancer
      - ../cluster/rsp-ha-rserver.conf:/etc/rstudio/rserver.conf
      - ../cluster/rsp-ha-database.conf:/etc/rstudio/database.conf
      - ../cluster/secure-cookie-key:/etc/rstudio/secure-cookie-key
      - ../cluster/launcher-ha.conf:/etc/rstudio/launcher.conf
      - ../cluster/launcher.pem:/etc/rstudio/launcher.pem
      - ../cluster/launcher.pub:/etc/rstudio/launcher.pub
      - rsp-home-vol:/home
      - launcher-scratch:/var/lib/rstudio-launcher/Local
    command: ["wait-for-it.sh", "pg-rsp:5432", "--", "/usr/local/bin/startup.sh"]
    depends_on:
      - pg-rsp

  rsp2:
    hostname: rsp2
    image: rstudio/rstudio-workbench:${RSTUDIO_VERSION}
    privileged: true
    environment:
      RSP_LICENSE: ${RSP_LICENSE}
    ports:
       - "8787"
    volumes:
      - ../cluster/rsp-load-balancer:/etc/rstudio/load-balancer
      - ../cluster/rsp-ha-rserver.conf:/etc/rstudio/rserver.conf
      - ../cluster/rsp-ha-database.conf:/etc/rstudio/database.conf
      - ../cluster/secure-cookie-key:/etc/rstudio/secure-cookie-key
      - ../cluster/launcher-ha.conf:/etc/rstudio/launcher.conf
      - ../cluster/launcher.pem:/etc/rstudio/launcher.pem
      - ../cluster/launcher.pub:/etc/rstudio/launcher.pub
      - rsp-home-vol:/home
      - launcher-scratch:/var/lib/rstudio-launcher/Local
    command: ["wait-for-it.sh", "pg-rsp:5432", "--", "/usr/local/bin/startup.sh"]
    depends_on:
      - pg-rsp
      - rsp1

  proxy:
    image: nginx
    ports:
      - "80:80"
    volumes:
          - ../cluster/nginx-rsp-ha.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - rsp1
      - rsp2

  pg-rsp:
    hostname: pg-rsp
    image: postgres:10
    environment:
      POSTGRES_PASSWORD: test
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ../cluster/pg-init-rstudio.sh:/docker-entrypoint-initdb.d/init-db.sh

volumes:
  rsp-home-vol:
  launcher-scratch:
