version: '2.3'
services:

  connect:
    hostname: connect
    image: rstudio/sol-eng-connect:${CONNECT_VERSION}
    ports:
      - "3939:3939"
    privileged: true
    environment:
      - CONNECT_LICENSE
    volumes:
      - ../cluster/saml-connect-local.gcfg:/etc/rstudio-connect/rstudio-connect.gcfg
