version: '2.3'
services:
  cfssl:
    hostname: cfssl
    image: cfssl/cfssl
    command: ["serve", "-ca", "/myCA.pem", "-ca-key", "/myCA.key", "-address", "cfssl"]
    volumes: 
      - ../cluster/myCA.key.insecure:/myCA.key
      - ../cluster/myCA.pem:/myCA.pem

