version: '3.7'
services:

  ssp1:
    hostname: ssp1
    build:
      args:
       - SSP_VERSION
      context: ../cluster
      dockerfile: base-ssp/Dockerfile
    image: rstudio/sol-eng-shiny-server:${SSP_VERSION}
    environment:
      - SSP_LICENSE
    ports:
      - "3838"
    volumes:
      - "../cluster/ssp-basic.conf:/etc/shiny-server/shiny-server.conf"
    command:
      - "shiny-server"
      - "/etc/shiny-server/shiny-server.conf"
  ssp2:
    hostname: ssp1
    build:
      args:
       - SSP_VERSION
      context: ../cluster
      dockerfile: base-ssp/Dockerfile
    image: rstudio/sol-eng-shiny-server:${SSP_VERSION}
    environment:
      - SSP_LICENSE
    ports:
      - "3838"
    volumes:
      - "../cluster/ssp-basic.conf:/etc/shiny-server/shiny-server.conf"
    command:
      - "shiny-server"
      - "/etc/shiny-server/shiny-server.conf"

