{
 "title": "RSP Dashboard - All",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "query": "label_values(node_boot_time, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Active Sessions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rstudio_server_pro_active_sessions{instance=~\"$node\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "avg(rstudio_server_pro_active_sessions{instance=~\"$node\"})",
     "legendFormat": "Average"
    },
    {
     "expr": "quantile(0.5, rstudio_server_pro_active_sessions{instance=~\"$node\"})",
     "legendFormat": "Median"
    }
   ]
  },
  {
   "title": "Active Sessions (Servers > Threshold)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(rstudio_server_pro_active_sessions{instance=~\"$node\"} >= 1)",
     "legendFormat": ">= 1"
    },
    {
     "expr": "count(rstudio_server_pro_active_sessions{instance=~\"$node\"} > 3)",
     "legendFormat": "> 3"
    },
    {
     "expr": "count(rstudio_server_pro_active_sessions{instance=~\"$node\"} > 5)"
    }
   ]
  },
  {
   "title": "Memory Percent",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(rstudio_server_pro_memory_percent{instance=~\"$node\"})",
     "legendFormat": "Max"
    },
    {
     "expr": "avg(rstudio_server_pro_memory_percent{instance=~\"$node\"})",
     "legendFormat": "Average"
    },
    {
     "expr": "quantile(0.5,rstudio_server_pro_memory_percent{instance=~\"$node\"})",
     "legendFormat": "Median"
    }
   ]
  },
  {
   "title": "Memory Percent (Servers > Threshold)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(rstudio_server_pro_memory_percent{instance=~\"$node\"} > 5)",
     "legendFormat": "> 5"
    },
    {
     "expr": "count(rstudio_server_pro_memory_percent{instance=~\"$node\"} > 50)",
     "legendFormat": "> 50"
    },
    {
     "expr": "count(rstudio_server_pro_memory_percent{instance=~\"$node\"} > 75)",
     "legendFormat": "> 75"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(rstudio_server_pro_load_average{instance=~\"$node\"})",
     "legendFormat": "Max"
    },
    {
     "expr": "avg(rstudio_server_pro_load_average{instance=~\"$node\"})",
     "legendFormat": "Average"
    },
    {
     "expr": "quantile(0.5,rstudio_server_pro_load_average{instance=~\"$node\"})",
     "legendFormat": "Median"
    }
   ]
  },
  {
   "title": "Load Average (Servers > Threshold)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(rstudio_server_pro_load_average{instance=~\"$node\"} > 0.1)",
     "legendFormat": "> 0.1"
    },
    {
     "expr": "count(rstudio_server_pro_load_average{instance=~\"$node\"} > 0.5)",
     "legendFormat": "> 0.5"
    },
    {
     "expr": "count(rstudio_server_pro_load_average{instance=~\"$node\"} > 0.75)",
     "legendFormat": "> 0.75"
    }
   ]
  },
  {
   "title": "CPU Percent",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(rstudio_server_pro_cpu_percent{instance=~\"$node\"})",
     "legendFormat": "Max"
    },
    {
     "expr": "avg(rstudio_server_pro_cpu_percent{instance=~\"$node\"})",
     "legendFormat": "Average"
    },
    {
     "expr": "quantile(0.5,rstudio_server_pro_cpu_percent{instance=~\"$node\"})",
     "legendFormat": "Median"
    }
   ]
  },
  {
   "title": "CPU Percent (Servers > Threshold)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(rstudio_server_pro_cpu_percent{instance=~\"$node\"} > 10)",
     "legendFormat": "> 10"
    },
    {
     "expr": "count(rstudio_server_pro_cpu_percent{instance=~\"$node\"} > 50)",
     "legendFormat": "> 50"
    },
    {
     "expr": "count(rstudio_server_pro_cpu_percent{instance=~\"$node\"} > 75)",
     "legendFormat": "> 75"
    }
   ]
  },
  {
   "title": "Idle Minutes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(rstudio_server_pro_idle_seconds{instance=~\"$node\"} / 60)",
     "legendFormat": "Max"
    },
    {
     "expr": "avg(rstudio_server_pro_idle_seconds{instance=~\"$node\"} / 60)",
     "legendFormat": "Average"
    },
    {
     "expr": "quantile(0.5, (rstudio_server_pro_idle_seconds{instance=~\"$node\"} / 60))",
     "legendFormat": "Median"
    }
   ]
  },
  {
   "title": "Idle Minutes (Servers > Threshold)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count((rstudio_server_pro_idle_seconds{instance=~\"$node\"} / 60) > 5)",
     "legendFormat": "> 5"
    },
    {
     "expr": "count((rstudio_server_pro_idle_seconds{instance=~\"$node\"} / 60) > 30)",
     "legendFormat": "> 30"
    },
    {
     "expr": "count((rstudio_server_pro_idle_seconds{instance=~\"$node\"} / 60) > 120)",
     "legendFormat": "> 120"
    }
   ]
  },
  {
   "title": "Swap Percent",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(rstudio_server_pro_swap_percent{instance=~\"$node\"})",
     "legendFormat": "Max"
    },
    {
     "expr": "avg(rstudio_server_pro_swap_percent{instance=~\"$node\"})",
     "legendFormat": "Average"
    },
    {
     "expr": "quantile(0.5,rstudio_server_pro_swap_percent{instance=~\"$node\"})",
     "legendFormat": "Median"
    }
   ]
  },
  {
   "title": "Swap Percent (Servers > Threshold)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(rstudio_server_pro_swap_percent{instance=~\"$node\"} > 10)",
     "legendFormat": "> 10"
    },
    {
     "expr": "count(rstudio_server_pro_swap_percent{instance=~\"$node\"} > 50)",
     "legendFormat": "> 50"
    },
    {
     "expr": "count(rstudio_server_pro_swap_percent{instance=~\"$node\"} > 75)",
     "legendFormat": "> 75"
    }
   ]
  }
 ]
}