#!/usr/bin/with-contenv bash
## load /etc/environment vars first:
 for line in $( cat /etc/environment ) ; do export $line ; done

if [ -z "${RSP_LICENSE}" ]; then
    echo >&2 'error: The RSP_LICENSE variable is not set.'
    exit 1
fi

activate() {
    echo "Activating license ..."
    /usr/lib/rstudio-server/bin/license-manager activate $RSP_LICENSE 2>&1
    if [ $? -ne 0 ]
    then
        echo >&2 'error: RSP_LICENSE could not be activated.'
        exit 1
    fi     
}

# start sssd
# we should really be a bit more sophisticated...
sssd

activate

exec /usr/lib/rstudio-server/bin/rserver --server-daemonize 0
